---
title: "06-ggplot"
author: "Lanning"
date: "`r Sys.Date()`"
output: html_document
---

# visualization in R with ggplot

## r dialects

There are several approaches to graphics (and everything else!) in r; see [syntax cheatsheet](http://www.science.smith.edu/~amcnamara/Syntax-cheatsheet.pdf).  

The layout of this sheet is informative (one, two, and many variables X continuous vs categorical/discrete), and it provides a nice way of mapping out the domain. 

Base R includes one syntax for plotting which is still in wide use.  ggplot2, part of the tidyverse, is a second approach and the one we will consider here.see R4DS, Chapters 2 and 3

this will take two meetings



## ggplot

(see the **data visualization cheatsheet** on Slack)

Ggplot is a layered system of graphics. goal is to come up with some rules for good graphs, and a syntax with which to understand it

## playing with ggplot2

play along with Chapter 3

get ggplot2 to work

exercises 3.2.4 (what do you see?)

exercises 3.3.1 (a little further)

## playing with new data

get data - sources include https://github.com/idc9/stor390 and online data sets in R

pull out no more than five variables from the dataset

### 3.4 multivariate data

exercises 3.5.1