---
title: "reshapeAnscombe"
author: "Lanning"
date: "January 27, 2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup}
library (tidyverse)
data()
data(anscombe)
str(anscombe)
head(anscombe)
```

Reshaping Anscombe for us
```{r}
anscombe$kid <- c("Al", "Barb",
                   "Cathy", "Dirk",
                   "Edwin", "Flo",
                   "George", "Henry",
                   "Isaiah", "Jim",
                   "Ken") 
# make a file anscombe2 from anscombe
anscombe2 <- anscombe %>%
# make a new variable called x from x1:x4    
    gather(x,levelx,x1,x2,x3,x4,
# don't mess with the other variables
           -c(y1,y2,y3,y4,kid))
# peek at it
head(anscombe2)
anscombe2 <- anscombe2 %>% 
    gather(y,levely,y1,y2,y3,y4,
           -c(x,levelx,kid)) %>% 
# keep only pairs where the x and y vars are the same
    filter (substr(x,2,2) == substr(y,2,2)) %>% 
# drop one of these 
    select (-y) %>% 
    mutate(x = recode(x,
                      x1="Mon",x2 = "Tue",
                      x3 = "Wed", x4 = "Thu"))
head(anscombe2)
str(anscombe2)
```

