<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>19 prediction and classification | Data science for the liberal arts</title>
  <meta name="description" content="Test" />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="19 prediction and classification | Data science for the liberal arts" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="chihuahuamuffin.jpg" />
  <meta property="og:description" content="Test" />
  <meta name="github-repo" content="kevinlanning/DataSciLibArts" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="19 prediction and classification | Data science for the liberal arts" />
  
  <meta name="twitter:description" content="Test" />
  <meta name="twitter:image" content="chihuahuamuffin.jpg" />

<meta name="author" content="Kevin Lanning" />


<meta name="date" content="2020-04-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="cross-validation.html"/>
<link rel="next" href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.2.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script>
<link href="libs/str_view-0.1.0/str_view.css" rel="stylesheet" />
<script src="libs/str_view-binding-1.4.0/str_view.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Science for the Liberal Arts</a></li>

<li class="divider"></li>
<li><a href="index.html#section"></a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>preface</a><ul>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#some-features-of-the-text"><i class="fa fa-check"></i>some features of the text</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#the-book-is-for-you"><i class="fa fa-check"></i>the book is for you</a></li>
</ul></li>
<li class="part"><span><b>I Introduction</b></span></li>
<li class="chapter" data-level="1" data-path="data-science-for-the-liberal-arts.html"><a href="data-science-for-the-liberal-arts.html"><i class="fa fa-check"></i><b>1</b> data science for the liberal arts</a><ul>
<li class="chapter" data-level="1.1" data-path="data-science-for-the-liberal-arts.html"><a href="data-science-for-the-liberal-arts.html#type-c-data-science-data-science-for-the-liberal-arts"><i class="fa fa-check"></i><b>1.1</b> type C data science = data science for the liberal arts</a></li>
<li class="chapter" data-level="1.2" data-path="data-science-for-the-liberal-arts.html"><a href="data-science-for-the-liberal-arts.html#the-incompleteness-of-the-data-science-venn-diagram"><i class="fa fa-check"></i><b>1.2</b> the incompleteness of the data science Venn diagram</a></li>
<li class="chapter" data-level="1.3" data-path="data-science-for-the-liberal-arts.html"><a href="data-science-for-the-liberal-arts.html#a-dimension-of-depth"><i class="fa fa-check"></i><b>1.3</b> a dimension of depth</a></li>
<li class="chapter" data-level="1.4" data-path="data-science-for-the-liberal-arts.html"><a href="data-science-for-the-liberal-arts.html#google-and-the-liberal-arts"><i class="fa fa-check"></i><b>1.4</b> Google and the liberal arts</a></li>
<li class="chapter" data-level="1.5" data-path="data-science-for-the-liberal-arts.html"><a href="data-science-for-the-liberal-arts.html#data-sci-and-tmi"><i class="fa fa-check"></i><b>1.5</b> data sci and TMI</a></li>
<li class="chapter" data-level="1.6" data-path="data-science-for-the-liberal-arts.html"><a href="data-science-for-the-liberal-arts.html#discussion-what-will-you-do-with-data-science"><i class="fa fa-check"></i><b>1.6</b> discussion: what will you do with data science?</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>2</b> getting started</a><ul>
<li class="chapter" data-level="2.1" data-path="getting-started.html"><a href="getting-started.html#are-you-already-a-programmer-and-statistician"><i class="fa fa-check"></i><b>2.1</b> are you already a programmer and statistician?</a></li>
<li class="chapter" data-level="2.2" data-path="getting-started.html"><a href="getting-started.html#setting-up-your-machine-some-basic-tools"><i class="fa fa-check"></i><b>2.2</b> setting up your machine: some basic tools</a></li>
<li class="chapter" data-level="2.3" data-path="getting-started.html"><a href="getting-started.html#a-modified-15-minute-rule"><i class="fa fa-check"></i><b>2.3</b> a modified 15-minute rule</a></li>
<li class="chapter" data-level="2.4" data-path="getting-started.html"><a href="getting-started.html#discussion-who-deserves-a-good-grade"><i class="fa fa-check"></i><b>2.4</b> discussion: who deserves a good grade?</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="r-stands-for.html"><a href="r-stands-for.html"><i class="fa fa-check"></i><b>3</b> R stands for …</a><ul>
<li class="chapter" data-level="3.1" data-path="r-stands-for.html"><a href="r-stands-for.html#a-few-characteristics-of-r"><i class="fa fa-check"></i><b>3.1</b> a few characteristics of R</a></li>
<li class="chapter" data-level="3.2" data-path="r-stands-for.html"><a href="r-stands-for.html#finding-help"><i class="fa fa-check"></i><b>3.2</b> finding help</a></li>
<li class="chapter" data-level="3.3" data-path="r-stands-for.html"><a href="r-stands-for.html#wickham-and-r-for-data-science"><i class="fa fa-check"></i><b>3.3</b> Wickham and R for Data Science</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html"><i class="fa fa-check"></i><b>4</b> now draw the rest of the owl</a><ul>
<li class="chapter" data-level="4.1" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html#carmichael"><i class="fa fa-check"></i><b>4.1</b> Carmichael</a></li>
<li class="chapter" data-level="4.2" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html#datacamp"><i class="fa fa-check"></i><b>4.2</b> DataCamp</a></li>
<li class="chapter" data-level="4.3" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html#swirl-swirlstats"><i class="fa fa-check"></i><b>4.3</b> Swirl (Swirlstats)</a></li>
<li class="chapter" data-level="4.4" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html#peng-text-and-videos"><i class="fa fa-check"></i><b>4.4</b> Peng text and videos</a></li>
<li class="chapter" data-level="4.5" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html#something-else"><i class="fa fa-check"></i><b>4.5</b> Something else</a></li>
<li class="chapter" data-level="4.6" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html#an-exercise"><i class="fa fa-check"></i><b>4.6</b> An exercise</a><ul>
<li class="chapter" data-level="4.6.1" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html#an-initial-solution"><i class="fa fa-check"></i><b>4.6.1</b> An initial solution</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html#an-introduction-to-r-markdown"><i class="fa fa-check"></i><b>4.7</b> An introduction to R markdown</a><ul>
<li class="chapter" data-level="4.7.1" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html#step-by-step"><i class="fa fa-check"></i><b>4.7.1</b> Step-by-step</a></li>
<li class="chapter" data-level="4.7.2" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html#spilled"><i class="fa fa-check"></i><b>4.7.2</b> Spilled???</a></li>
<li class="chapter" data-level="4.7.3" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html#your-turn"><i class="fa fa-check"></i><b>4.7.3</b> Your turn</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Part II Towards data literacy</b></span></li>
<li class="chapter" data-level="5" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html"><i class="fa fa-check"></i><b>5</b> Principles of data visualization</a><ul>
<li class="chapter" data-level="5.1" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#some-opening-thoughts"><i class="fa fa-check"></i><b>5.1</b> Some opening thoughts</a></li>
<li class="chapter" data-level="5.2" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#some-early-graphs"><i class="fa fa-check"></i><b>5.2</b> Some early graphs</a></li>
<li class="chapter" data-level="5.3" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#tukey-and-eda"><i class="fa fa-check"></i><b>5.3</b> Tukey and EDA</a></li>
<li class="chapter" data-level="5.4" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#approaches-to-graphs"><i class="fa fa-check"></i><b>5.4</b> Approaches to graphs</a></li>
<li class="chapter" data-level="5.5" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#tufte-first-principles"><i class="fa fa-check"></i><b>5.5</b> Tufte: First principles</a></li>
<li class="chapter" data-level="5.6" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#the-politics-of-data-visualization"><i class="fa fa-check"></i><b>5.6</b> The politics of data visualization</a><ul>
<li class="chapter" data-level="5.6.1" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#poor-design-leads-to-an-uninformed-or-misinformed-world"><i class="fa fa-check"></i><b>5.6.1</b> Poor design leads to an uninformed or misinformed world</a></li>
<li class="chapter" data-level="5.6.2" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#poor-design-can-be-a-tool-to-deceive"><i class="fa fa-check"></i><b>5.6.2</b> Poor design can be a tool to deceive</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#the-psychology-of-data-visualization"><i class="fa fa-check"></i><b>5.7</b> The psychology of data visualization</a><ul>
<li class="chapter" data-level="5.7.1" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#the-power-of-animation"><i class="fa fa-check"></i><b>5.7.1</b> The power of animation</a></li>
<li class="chapter" data-level="5.7.2" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#telling-the-truth-when-the-truth-is-unclear"><i class="fa fa-check"></i><b>5.7.2</b> Telling the truth when the truth is unclear</a></li>
<li class="chapter" data-level="5.7.3" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#visualizing-uncertainty"><i class="fa fa-check"></i><b>5.7.3</b> Visualizing uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#further-reading-and-resources"><i class="fa fa-check"></i><b>5.8</b> further reading and resources</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html"><i class="fa fa-check"></i><b>6</b> visualization in R with ggplot</a><ul>
<li class="chapter" data-level="6.1" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html#a-picture-words-numbers"><i class="fa fa-check"></i><b>6.1</b> a picture &gt; (words, numbers)?</a></li>
<li class="chapter" data-level="6.2" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html#read-hadley-ggplots"><i class="fa fa-check"></i><b>6.2</b> Read Hadley ggplots</a></li>
<li class="chapter" data-level="6.3" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html#exploring-more-data"><i class="fa fa-check"></i><b>6.3</b> exploring more data</a></li>
<li class="chapter" data-level="6.4" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html#advanced-tracking-the-novel-coronavirus"><i class="fa fa-check"></i><b>6.4</b> Advanced: Tracking the Novel Coronavirus</a><ul>
<li class="chapter" data-level="6.4.1" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html#reading-the-data"><i class="fa fa-check"></i><b>6.4.1</b> Reading the data</a></li>
<li class="chapter" data-level="6.4.2" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html#cleaning-wrangling-munging-the-data"><i class="fa fa-check"></i><b>6.4.2</b> Cleaning (wrangling, munging) the data</a></li>
<li class="chapter" data-level="6.4.3" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html#simplifying-the-data-china-and-the-rest-of-the-world"><i class="fa fa-check"></i><b>6.4.3</b> Simplifying the data: China and the rest of the world</a></li>
<li class="chapter" data-level="6.4.4" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html#an-initial-plot"><i class="fa fa-check"></i><b>6.4.4</b> An initial plot</a></li>
<li class="chapter" data-level="6.4.5" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html#adding-recovered-cases"><i class="fa fa-check"></i><b>6.4.5</b> Adding recovered cases</a></li>
<li class="chapter" data-level="6.4.6" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html#make-the-graph-interactive"><i class="fa fa-check"></i><b>6.4.6</b> Make the graph interactive</a></li>
<li class="chapter" data-level="6.4.7" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html#plotting-confirmed-cases"><i class="fa fa-check"></i><b>6.4.7</b> Plotting confirmed cases</a></li>
<li class="chapter" data-level="6.4.8" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html#some-questions"><i class="fa fa-check"></i><b>6.4.8</b> Some questions</a></li>
<li class="chapter" data-level="6.4.9" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html#additional-notes"><i class="fa fa-check"></i><b>6.4.9</b> Additional notes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html"><i class="fa fa-check"></i><b>7</b> on probability and statistics</a><ul>
<li class="chapter" data-level="7.1" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#on-probability"><i class="fa fa-check"></i><b>7.1</b> on probability</a></li>
<li class="chapter" data-level="7.2" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#the-rules-of-probability"><i class="fa fa-check"></i><b>7.2</b> the rules of probability</a><ul>
<li class="chapter" data-level="7.2.1" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#keeping-conditional-probabilities-straight"><i class="fa fa-check"></i><b>7.2.1</b> keeping conditional probabilities straight</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#continuous-probability-distributions"><i class="fa fa-check"></i><b>7.3</b> continuous probability distributions</a></li>
<li class="chapter" data-level="7.4" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#the-most-dangerous-equation"><i class="fa fa-check"></i><b>7.4</b> the most dangerous equation</a></li>
<li class="chapter" data-level="7.5" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#appendix-notes-on-discrete-probability"><i class="fa fa-check"></i><b>7.5</b> appendix: notes on discrete probability</a></li>
<li class="chapter" data-level="7.6" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#discrete-probability-see-attribution-in-7.5"><i class="fa fa-check"></i><b>7.6</b> Discrete Probability (see attribution in 7.5)</a><ul>
<li class="chapter" data-level="7.6.1" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#relative-frequency"><i class="fa fa-check"></i><b>7.6.1</b> Relative Frequency</a></li>
<li class="chapter" data-level="7.6.2" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#notation"><i class="fa fa-check"></i><b>7.6.2</b> Notation</a></li>
<li class="chapter" data-level="7.6.3" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#monte-carlo-simulations"><i class="fa fa-check"></i><b>7.6.3</b> Monte Carlo Simulations</a></li>
<li class="chapter" data-level="7.6.4" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#with-and-without-replacement"><i class="fa fa-check"></i><b>7.6.4</b> With and without replacement</a></li>
<li class="chapter" data-level="7.6.5" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#probability-distributions"><i class="fa fa-check"></i><b>7.6.5</b> Probability Distributions</a></li>
<li class="chapter" data-level="7.6.6" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#independence"><i class="fa fa-check"></i><b>7.6.6</b> Independence</a></li>
<li class="chapter" data-level="7.6.7" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#conditional-probabilities"><i class="fa fa-check"></i><b>7.6.7</b> Conditional Probabilities</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#multiplication-rule-see-attribution-in-7.5"><i class="fa fa-check"></i><b>7.7</b> Multiplication rule (see attribution in 7.5)</a><ul>
<li class="chapter" data-level="7.7.1" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#combinations-and-permutations"><i class="fa fa-check"></i><b>7.7.1</b> Combinations and Permutations</a></li>
<li class="chapter" data-level="7.7.2" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#birthday-problem"><i class="fa fa-check"></i><b>7.7.2</b> Birthday Problem</a></li>
<li class="chapter" data-level="7.7.3" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#sapply-a-better-way-to-do-for-loops"><i class="fa fa-check"></i><b>7.7.3</b> sapply: a better way to do for loops</a></li>
<li class="chapter" data-level="7.7.4" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#how-many-monte-carlo-experiments-are-enough"><i class="fa fa-check"></i><b>7.7.4</b> How many Monte Carlo experiments are enough</a></li>
<li class="chapter" data-level="7.7.5" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#addition-rule"><i class="fa fa-check"></i><b>7.7.5</b> Addition Rule</a></li>
<li class="chapter" data-level="7.7.6" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#monty-hall-problem"><i class="fa fa-check"></i><b>7.7.6</b> Monty Hall Problem</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="reproducibility-and-the-replication-crisis.html"><a href="reproducibility-and-the-replication-crisis.html"><i class="fa fa-check"></i><b>8</b> Reproducibility and the replication crisis</a><ul>
<li class="chapter" data-level="8.1" data-path="reproducibility-and-the-replication-crisis.html"><a href="reproducibility-and-the-replication-crisis.html#answers-to-the-reproducibility-crisis"><i class="fa fa-check"></i><b>8.1</b> Answers to the reproducibility crisis</a><ul>
<li class="chapter" data-level="8.1.1" data-path="reproducibility-and-the-replication-crisis.html"><a href="reproducibility-and-the-replication-crisis.html#tweak-or-abandon-nhst"><i class="fa fa-check"></i><b>8.1.1</b> Tweak or abandon NHST</a></li>
<li class="chapter" data-level="8.1.2" data-path="reproducibility-and-the-replication-crisis.html"><a href="reproducibility-and-the-replication-crisis.html#keep-a-log-of-every-step-of-every-analysis-in-r-markdown-or-jupyter-notebooks"><i class="fa fa-check"></i><b>8.1.2</b> Keep a log of every step of every analysis in R markdown or Jupyter notebooks</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="reproducibility-and-the-replication-crisis.html"><a href="reproducibility-and-the-replication-crisis.html#answers-to-the-reproducibility-crisis-iii-pre-registration"><i class="fa fa-check"></i><b>8.2</b> Answers to the reproducibility crisis III: Pre-registration</a></li>
<li class="chapter" data-level="8.3" data-path="reproducibility-and-the-replication-crisis.html"><a href="reproducibility-and-the-replication-crisis.html#further-readings"><i class="fa fa-check"></i><b>8.3</b> Further readings</a></li>
</ul></li>
<li class="part"><span><b>III Part III Towards data proficiency</b></span></li>
<li class="chapter" data-level="9" data-path="literate-programming-with-r-markdown.html"><a href="literate-programming-with-r-markdown.html"><i class="fa fa-check"></i><b>9</b> literate programming with R markdown</a><ul>
<li class="chapter" data-level="9.1" data-path="literate-programming-with-r-markdown.html"><a href="literate-programming-with-r-markdown.html#scripts-are-files-of-code"><i class="fa fa-check"></i><b>9.1</b> scripts are files of code</a><ul>
<li class="chapter" data-level="9.1.1" data-path="literate-programming-with-r-markdown.html"><a href="literate-programming-with-r-markdown.html#some-elements-of-coding-style"><i class="fa fa-check"></i><b>9.1.1</b> some elements of coding style</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="literate-programming-with-r-markdown.html"><a href="literate-programming-with-r-markdown.html#projects-are-directories-containing-related-scripts"><i class="fa fa-check"></i><b>9.2</b> projects are directories containing related scripts</a></li>
<li class="chapter" data-level="9.3" data-path="literate-programming-with-r-markdown.html"><a href="literate-programming-with-r-markdown.html#r-markdown-documents-integrate-rationale-script-and-results"><i class="fa fa-check"></i><b>9.3</b> R markdown documents integrate rationale, script, and results</a></li>
<li class="chapter" data-level="9.4" data-path="literate-programming-with-r-markdown.html"><a href="literate-programming-with-r-markdown.html#what-to-do-when-you-are-stuck"><i class="fa fa-check"></i><b>9.4</b> What to do when you are stuck</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="the-tidyverse.html"><a href="the-tidyverse.html"><i class="fa fa-check"></i><b>10</b> the tidyverse</a><ul>
<li class="chapter" data-level="10.1" data-path="the-tidyverse.html"><a href="the-tidyverse.html#some-simple-principles"><i class="fa fa-check"></i><b>10.1</b> some simple principles</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="finding-exploring-and-cleaning-data.html"><a href="finding-exploring-and-cleaning-data.html"><i class="fa fa-check"></i><b>11</b> finding, exploring, and cleaning data</a><ul>
<li class="chapter" data-level="11.1" data-path="finding-exploring-and-cleaning-data.html"><a href="finding-exploring-and-cleaning-data.html#data-in-r-libraries"><i class="fa fa-check"></i><b>11.1</b> Data in R libraries</a></li>
<li class="chapter" data-level="11.2" data-path="finding-exploring-and-cleaning-data.html"><a href="finding-exploring-and-cleaning-data.html#other-prepared-datasets"><i class="fa fa-check"></i><b>11.2</b> Other prepared datasets</a></li>
<li class="chapter" data-level="11.3" data-path="finding-exploring-and-cleaning-data.html"><a href="finding-exploring-and-cleaning-data.html#makeextractcombine-your-own-data"><i class="fa fa-check"></i><b>11.3</b> Make/extract/combine your own data</a></li>
<li class="chapter" data-level="11.4" data-path="finding-exploring-and-cleaning-data.html"><a href="finding-exploring-and-cleaning-data.html#exploring-data"><i class="fa fa-check"></i><b>11.4</b> exploring data</a></li>
<li class="chapter" data-level="11.5" data-path="finding-exploring-and-cleaning-data.html"><a href="finding-exploring-and-cleaning-data.html#messy-data-cleaning-and-curation"><i class="fa fa-check"></i><b>11.5</b> messy data: Cleaning and curation</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="transforming-data.html"><a href="transforming-data.html"><i class="fa fa-check"></i><b>12</b> transforming data</a><ul>
<li class="chapter" data-level="12.1" data-path="transforming-data.html"><a href="transforming-data.html#from-data-on-the-web-to-data-in-r"><i class="fa fa-check"></i><b>12.1</b> from data on the web to data in R</a></li>
<li class="chapter" data-level="12.2" data-path="transforming-data.html"><a href="transforming-data.html#working-with-geodata-a-function-to-get-us-states-from-latitudelongitude"><i class="fa fa-check"></i><b>12.2</b> working with geodata: a function to get US states from latitude/longitude</a><ul>
<li class="chapter" data-level="12.2.1" data-path="transforming-data.html"><a href="transforming-data.html#applying-the-function-to-the-music-data"><i class="fa fa-check"></i><b>12.2.1</b> applying the function to the music data</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="transforming-data.html"><a href="transforming-data.html#drowning-in-the-sea-of-songs-with-apologies-to-arivoim1187b990643"><i class="fa fa-check"></i><b>12.3</b> drowning in the sea of songs (with apologies to <em>ARIVOIM1187B990643</em>)</a><ul>
<li class="chapter" data-level="12.3.1" data-path="transforming-data.html"><a href="transforming-data.html#combining-the-song-titles-with-our-us-artists"><i class="fa fa-check"></i><b>12.3.1</b> combining the song titles with our US artists</a></li>
<li class="chapter" data-level="12.3.2" data-path="transforming-data.html"><a href="transforming-data.html#exercises"><i class="fa fa-check"></i><b>12.3.2</b> exercises</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="transforming-data.html"><a href="transforming-data.html#review-of-munging-tools"><i class="fa fa-check"></i><b>12.4</b> review of munging tools</a><ul>
<li class="chapter" data-level="12.4.1" data-path="transforming-data.html"><a href="transforming-data.html#and-still-more-munging"><i class="fa fa-check"></i><b>12.4.1</b> and still more munging</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="an-interlude.html"><a href="an-interlude.html"><i class="fa fa-check"></i><b>13</b> an interlude</a><ul>
<li class="chapter" data-level="13.1" data-path="an-interlude.html"><a href="an-interlude.html#global-data"><i class="fa fa-check"></i><b>13.1</b> global data</a></li>
<li class="chapter" data-level="13.2" data-path="an-interlude.html"><a href="an-interlude.html#florida-data"><i class="fa fa-check"></i><b>13.2</b> Florida data</a></li>
<li class="chapter" data-level="13.3" data-path="an-interlude.html"><a href="an-interlude.html#network-models"><i class="fa fa-check"></i><b>13.3</b> network models</a></li>
<li class="chapter" data-level="13.4" data-path="an-interlude.html"><a href="an-interlude.html#back-to-r-relational-data"><i class="fa fa-check"></i><b>13.4</b> back to R: relational data</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="strings-factors-dates-and-times.html"><a href="strings-factors-dates-and-times.html"><i class="fa fa-check"></i><b>14</b> strings, factors, dates, and times</a><ul>
<li class="chapter" data-level="14.1" data-path="strings-factors-dates-and-times.html"><a href="strings-factors-dates-and-times.html#strings"><i class="fa fa-check"></i><b>14.1</b> strings</a></li>
<li class="chapter" data-level="14.2" data-path="strings-factors-dates-and-times.html"><a href="strings-factors-dates-and-times.html#factors"><i class="fa fa-check"></i><b>14.2</b> factors</a><ul>
<li class="chapter" data-level="14.2.1" data-path="strings-factors-dates-and-times.html"><a href="strings-factors-dates-and-times.html#types-of-babies"><i class="fa fa-check"></i><b>14.2.1</b> types of babies</a></li>
<li class="chapter" data-level="14.2.2" data-path="strings-factors-dates-and-times.html"><a href="strings-factors-dates-and-times.html#types-of-grown-ups"><i class="fa fa-check"></i><b>14.2.2</b> types of grown-ups</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="strings-factors-dates-and-times.html"><a href="strings-factors-dates-and-times.html#dates"><i class="fa fa-check"></i><b>14.3</b> dates</a></li>
<li class="chapter" data-level="14.4" data-path="strings-factors-dates-and-times.html"><a href="strings-factors-dates-and-times.html#times"><i class="fa fa-check"></i><b>14.4</b> times</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="lists.html"><a href="lists.html"><i class="fa fa-check"></i><b>15</b> lists</a></li>
<li class="chapter" data-level="16" data-path="loops-functions-and-beyond.html"><a href="loops-functions-and-beyond.html"><i class="fa fa-check"></i><b>16</b> loops, functions, and beyond</a><ul>
<li class="chapter" data-level="16.1" data-path="loops-functions-and-beyond.html"><a href="loops-functions-and-beyond.html#loops"><i class="fa fa-check"></i><b>16.1</b> loops</a></li>
<li class="chapter" data-level="16.2" data-path="loops-functions-and-beyond.html"><a href="loops-functions-and-beyond.html#from-loop-to-apply-to-purrrmap"><i class="fa fa-check"></i><b>16.2</b> from loop to apply to purrr::map</a></li>
<li class="chapter" data-level="16.3" data-path="loops-functions-and-beyond.html"><a href="loops-functions-and-beyond.html#some-examples-of-functions"><i class="fa fa-check"></i><b>16.3</b> some examples of functions</a><ul>
<li class="chapter" data-level="16.3.1" data-path="loops-functions-and-beyond.html"><a href="loops-functions-and-beyond.html#preliminaries"><i class="fa fa-check"></i><b>16.3.1</b> preliminaries</a></li>
<li class="chapter" data-level="16.3.2" data-path="loops-functions-and-beyond.html"><a href="loops-functions-and-beyond.html#the-function"><i class="fa fa-check"></i><b>16.3.2</b> the function</a></li>
<li class="chapter" data-level="16.3.3" data-path="loops-functions-and-beyond.html"><a href="loops-functions-and-beyond.html#applying-the-function"><i class="fa fa-check"></i><b>16.3.3</b> applying the function</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="loops-functions-and-beyond.html"><a href="loops-functions-and-beyond.html#how-many-bottles-of-what"><i class="fa fa-check"></i><b>16.4</b> how many bottles of what?</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="correlation-and-linear-regression.html"><a href="correlation-and-linear-regression.html"><i class="fa fa-check"></i><b>17</b> correlation and linear regression</a><ul>
<li class="chapter" data-level="17.1" data-path="correlation-and-linear-regression.html"><a href="correlation-and-linear-regression.html#correlation"><i class="fa fa-check"></i><b>17.1</b> correlation</a><ul>
<li class="chapter" data-level="17.1.1" data-path="correlation-and-linear-regression.html"><a href="correlation-and-linear-regression.html#the-regression-line"><i class="fa fa-check"></i><b>17.1.1</b> The regression line</a></li>
<li class="chapter" data-level="17.1.2" data-path="correlation-and-linear-regression.html"><a href="correlation-and-linear-regression.html#warning-there-are-two-regression-lines"><i class="fa fa-check"></i><b>17.1.2</b> Warning: there are two regression lines</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="correlation-and-linear-regression.html"><a href="correlation-and-linear-regression.html#multiple-regression"><i class="fa fa-check"></i><b>17.2</b> multiple regression</a></li>
<li class="chapter" data-level="17.3" data-path="correlation-and-linear-regression.html"><a href="correlation-and-linear-regression.html#swiss-fertility-data"><i class="fa fa-check"></i><b>17.3</b> Swiss fertility data</a></li>
<li class="chapter" data-level="17.4" data-path="correlation-and-linear-regression.html"><a href="correlation-and-linear-regression.html#marital-affairs-data"><i class="fa fa-check"></i><b>17.4</b> marital affairs data</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="cross-validation.html"><a href="cross-validation.html"><i class="fa fa-check"></i><b>18</b> cross-validation</a><ul>
<li class="chapter" data-level="18.1" data-path="cross-validation.html"><a href="cross-validation.html#revisiting-the-affairs-data"><i class="fa fa-check"></i><b>18.1</b> revisiting the affairs data</a></li>
<li class="chapter" data-level="18.2" data-path="cross-validation.html"><a href="cross-validation.html#avoiding-capitalizing-on-chance"><i class="fa fa-check"></i><b>18.2</b> avoiding capitalizing on chance</a><ul>
<li class="chapter" data-level="18.2.1" data-path="cross-validation.html"><a href="cross-validation.html#splitting-the-data-into-training-and-test-subsamples"><i class="fa fa-check"></i><b>18.2.1</b> splitting the data into training and test subsamples</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="cross-validation.html"><a href="cross-validation.html#an-example-of-cross-validated-linear-regression"><i class="fa fa-check"></i><b>18.3</b> an example of cross-validated linear regression</a><ul>
<li class="chapter" data-level="18.3.1" data-path="cross-validation.html"><a href="cross-validation.html#applying-logistic-regression-analysis-to-the-training-data"><i class="fa fa-check"></i><b>18.3.1</b> applying logistic regression analysis to the training data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html"><i class="fa fa-check"></i><b>19</b> prediction and classification</a><ul>
<li class="chapter" data-level="19.1" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#from-regression-to-classification-selection-of-a-threshold"><i class="fa fa-check"></i><b>19.1</b> from regression to classification: selection of a threshold</a><ul>
<li class="chapter" data-level="19.1.1" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#applying-the-model-to-the-test-data"><i class="fa fa-check"></i><b>19.1.1</b> applying the model to the test data</a></li>
<li class="chapter" data-level="19.1.2" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#changing-our-decision-threshold"><i class="fa fa-check"></i><b>19.1.2</b> changing our decision threshold</a></li>
<li class="chapter" data-level="19.1.3" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#more-confusion"><i class="fa fa-check"></i><b>19.1.3</b> more confusion</a></li>
<li class="chapter" data-level="19.1.4" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#rocs-and-auc"><i class="fa fa-check"></i><b>19.1.4</b> ROCs and AUC</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#another-approach-to-classification-k-nearest-neighbor"><i class="fa fa-check"></i><b>19.2</b> another approach to classification: k-nearest neighbor</a><ul>
<li class="chapter" data-level="19.2.1" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#application-the-affairs-data"><i class="fa fa-check"></i><b>19.2.1</b> application: the affairs data</a></li>
<li class="chapter" data-level="19.2.2" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#from-one-doppelganger-to-many"><i class="fa fa-check"></i><b>19.2.2</b> from one doppelganger to many</a></li>
<li class="chapter" data-level="19.2.3" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#the-bayesian-classifier"><i class="fa fa-check"></i><b>19.2.3</b> the Bayesian classifier</a></li>
<li class="chapter" data-level="19.2.4" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#back-to-the-affairs-data"><i class="fa fa-check"></i><b>19.2.4</b> Back to the affairs data</a></li>
<li class="chapter" data-level="19.2.5" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#avoiding-capitalization-on-chance-again"><i class="fa fa-check"></i><b>19.2.5</b> avoiding capitalization on chance (again)</a></li>
<li class="chapter" data-level="19.2.6" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#the-multinomial-case"><i class="fa fa-check"></i><b>19.2.6</b> the multinomial case</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"><a href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"><i class="fa fa-check"></i><b>20</b> machine learning: chihuahuas vs muffins, and other distinctions and ideas</a><ul>
<li class="chapter" data-level="20.1" data-path="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"><a href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html#supervised-versus-unsupervised"><i class="fa fa-check"></i><b>20.1</b> supervised versus unsupervised</a></li>
<li class="chapter" data-level="20.2" data-path="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"><a href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html#prediction-versus-classification"><i class="fa fa-check"></i><b>20.2</b> prediction versus classification</a></li>
<li class="chapter" data-level="20.3" data-path="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"><a href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html#understanding-versus-prediction"><i class="fa fa-check"></i><b>20.3</b> understanding versus prediction</a></li>
<li class="chapter" data-level="20.4" data-path="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"><a href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html#bias-versus-variability"><i class="fa fa-check"></i><b>20.4</b> bias versus variability</a><ul>
<li class="chapter" data-level="20.4.1" data-path="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"><a href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html#resampling-beyond-test-training-and-validation-samples"><i class="fa fa-check"></i><b>20.4.1</b> resampling: beyond test, training, and validation samples</a></li>
</ul></li>
<li class="chapter" data-level="20.5" data-path="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"><a href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html#compensatory-versus-non-compensatory-problems"><i class="fa fa-check"></i><b>20.5</b> compensatory versus non-compensatory problems</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html"><i class="fa fa-check"></i><b>21</b> some ethical concerns for the data scientist</a><ul>
<li class="chapter" data-level="21.1" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html#ethics-and-personality-harvesting"><i class="fa fa-check"></i><b>21.1</b> ethics and personality harvesting</a></li>
<li class="chapter" data-level="21.2" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html#the-law-of-unintended-consequences"><i class="fa fa-check"></i><b>21.2</b> the law of unintended consequences</a></li>
<li class="chapter" data-level="21.3" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html#your-privacy-is-my-concern"><i class="fa fa-check"></i><b>21.3</b> your privacy is my concern</a></li>
<li class="chapter" data-level="21.4" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html#who-should-hold-the-digital-keys"><i class="fa fa-check"></i><b>21.4</b> who should hold the digital keys?</a></li>
<li class="chapter" data-level="21.5" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html#contact-tracing-and-covid-19"><i class="fa fa-check"></i><b>21.5</b> contact-tracing and COVID-19</a></li>
<li class="chapter" data-level="21.6" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html#the-digital-divide"><i class="fa fa-check"></i><b>21.6</b> the digital divide</a></li>
<li class="chapter" data-level="21.7" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html#some-potential-remedies"><i class="fa fa-check"></i><b>21.7</b> some potential remedies</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>22</b> references</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data science for the liberal arts</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="prediction-and-classification" class="section level1">
<h1><span class="header-section-number">19</span> prediction and classification</h1>
<p>If we want to classify people, we will need to create a decision threshold at which we will change our prediction from ‘no’ to ‘yes’.</p>
<div id="from-regression-to-classification-selection-of-a-threshold" class="section level2">
<h2><span class="header-section-number">19.1</span> from regression to classification: selection of a threshold</h2>
<p>We will continue to work with the affairs data; here’s the relevant code from last chapter:</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb225-1" title="1"><span class="co"># code from last chapter on Fair data</span></a>
<a class="sourceLine" id="cb225-2" title="2">Fair &lt;-<span class="st"> </span>Fair <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb225-3" title="3"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">rootAffair =</span> </a>
<a class="sourceLine" id="cb225-4" title="4">              <span class="kw">as.integer</span>(<span class="kw">sqrt</span>(nbaffairs))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb225-5" title="5"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">affairYN =</span></a>
<a class="sourceLine" id="cb225-6" title="6">               <span class="kw">ifelse</span> (nbaffairs <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>))</a>
<a class="sourceLine" id="cb225-7" title="7"><span class="kw">set.seed</span>(<span class="dv">33458</span>)</a>
<a class="sourceLine" id="cb225-8" title="8">n &lt;-<span class="st"> </span><span class="kw">nrow</span>(Fair)</a>
<a class="sourceLine" id="cb225-9" title="9">trainIndex &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span>n, <span class="dt">size =</span> <span class="kw">round</span>(<span class="fl">0.6</span><span class="op">*</span>n),</a>
<a class="sourceLine" id="cb225-10" title="10">                     <span class="dt">replace=</span><span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb225-11" title="11">trainFair &lt;-<span class="st"> </span>Fair[trainIndex ,]</a>
<a class="sourceLine" id="cb225-12" title="12">testFair &lt;-<span class="st"> </span>Fair[<span class="op">-</span>trainIndex ,]</a>
<a class="sourceLine" id="cb225-13" title="13">trainFair2 &lt;-<span class="st"> </span>trainFair <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb225-14" title="14"><span class="st">    </span><span class="kw">select</span>(<span class="op">-</span>nbaffairs, <span class="op">-</span>affairYN)</a>
<a class="sourceLine" id="cb225-15" title="15">testFair2 &lt;-<span class="st"> </span>testFair <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb225-16" title="16"><span class="st">    </span><span class="kw">select</span>(<span class="op">-</span>nbaffairs, <span class="op">-</span>affairYN)</a>
<a class="sourceLine" id="cb225-17" title="17">model2 &lt;-<span class="st"> </span><span class="kw">lm</span>(rootAffair <span class="op">~</span><span class="st"> </span>.,</a>
<a class="sourceLine" id="cb225-18" title="18">             <span class="dt">data =</span> trainFair2)</a>
<a class="sourceLine" id="cb225-19" title="19">predictTrain &lt;-<span class="st"> </span><span class="kw">predict</span>(model2, trainFair, </a>
<a class="sourceLine" id="cb225-20" title="20">                        <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)</a></code></pre></div>
<p>To maximise overall prediction, we will create a threshold equal to the actual proportion of people who don’t have affairs in our sample:</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb226-1" title="1">(threshold &lt;-<span class="st"> </span><span class="kw">mean</span>(trainFair<span class="op">$</span>affairYN))</a></code></pre></div>
<pre><code>## [1] 0.2548476</code></pre>
<p>This is equal to both the mean of our predicted scores (above) and the mean of our actual scores, and, because this is a dichotomous variable, the proportion of people in the sample who have affairs. We’ll predict that if a person has a predicted score more than this we’ll predict that s/he will be unfaithful, else we will “PredictOK.” Then we will create a <em>confusion matrix,</em> to compare our correct predictions (PredictOK and affairYN = 1, Predictunfaithful and affairYN = 0) with the remainder.</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb228-1" title="1">classification &lt;-<span class="st"> </span><span class="kw">ifelse</span>(predictTrain <span class="op">&gt;</span><span class="st"> </span>threshold,</a>
<a class="sourceLine" id="cb228-2" title="2">                         <span class="st">&quot;Predictunfaithful&quot;</span>, <span class="st">&quot;PredictOK&quot;</span>)</a>
<a class="sourceLine" id="cb228-3" title="3">(b &lt;-<span class="st"> </span><span class="kw">table</span>(classification, trainFair<span class="op">$</span>affairYN))</a></code></pre></div>
<pre><code>##                    
## classification        0   1
##   PredictOK         107  18
##   Predictunfaithful 162  74</code></pre>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb230-1" title="1">(correct &lt;-<span class="st"> </span>b[<span class="dv">1</span>,<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>b[<span class="dv">2</span>,<span class="dv">2</span>])</a></code></pre></div>
<pre><code>## [1] 181</code></pre>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb232-1" title="1">(errors &lt;-<span class="st"> </span>b[<span class="dv">1</span>,<span class="dv">2</span>] <span class="op">+</span><span class="st"> </span>b[<span class="dv">2</span>,<span class="dv">1</span>])</a></code></pre></div>
<pre><code>## [1] 180</code></pre>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb234-1" title="1">(accuracy &lt;-<span class="st"> </span>correct<span class="op">/</span>(correct <span class="op">+</span><span class="st"> </span>errors))</a></code></pre></div>
<pre><code>## [1] 0.501385</code></pre>
<div id="applying-the-model-to-the-test-data" class="section level3">
<h3><span class="header-section-number">19.1.1</span> applying the model to the test data</h3>
<p>We shouldn’t trust these results, though, because the model is based on the same data that it is tested upon. Now we will apply the model to the test data. With the linear regression model above, we examined ‘shrinkage’ in the overall R-square. Here, we can assess shrinkage in terms of the percent of erroneous classifications.</p>
<p>Typically (but not invariably), the percent of accurate classifications will decline, especially if the model is a complex one with many variables or if the number of observations is low.</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb236-1" title="1">predictTest &lt;-<span class="st"> </span><span class="kw">predict</span>(model2, testFair, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)</a>
<a class="sourceLine" id="cb236-2" title="2">classification &lt;-<span class="st"> </span><span class="kw">ifelse</span>(predictTest <span class="op">&gt;</span><span class="st"> </span>threshold,</a>
<a class="sourceLine" id="cb236-3" title="3">                         <span class="st">&quot;Predictunfaithful&quot;</span>, <span class="st">&quot;PredictOK&quot;</span>)</a>
<a class="sourceLine" id="cb236-4" title="4">(b &lt;-<span class="st"> </span><span class="kw">table</span>(classification, testFair<span class="op">$</span>affairYN))</a></code></pre></div>
<pre><code>##                    
## classification        0   1
##   PredictOK          73   9
##   Predictunfaithful 109  49</code></pre>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb238-1" title="1">(correct &lt;-<span class="st"> </span>b[<span class="dv">1</span>,<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>b[<span class="dv">2</span>,<span class="dv">2</span>])</a></code></pre></div>
<pre><code>## [1] 122</code></pre>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb240-1" title="1">(errors &lt;-<span class="st"> </span>b[<span class="dv">1</span>,<span class="dv">2</span>] <span class="op">+</span><span class="st"> </span>b[<span class="dv">2</span>,<span class="dv">1</span>])</a></code></pre></div>
<pre><code>## [1] 118</code></pre>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb242-1" title="1">(accuracy &lt;-<span class="st"> </span>correct<span class="op">/</span>(correct <span class="op">+</span><span class="st"> </span>errors))</a></code></pre></div>
<pre><code>## [1] 0.5083333</code></pre>
<p>On the test data, we are correct 51 percent of the time. This describes our <em>out of sample risk.</em></p>
</div>
<div id="changing-our-decision-threshold" class="section level3">
<h3><span class="header-section-number">19.1.2</span> changing our decision threshold</h3>
<p>In many decision problems, there is an asymmetry in the cost of different types of errors: if you are foraging for mushrooms, for example, an error of the form (you decide its safe and it is poisonous) is more costly than the converse (you decide its poisonous and it is safe).</p>
<p>This may be true in the present example as well. Consider someone who is looking for a spouse, but is really averse to the idea of getting hurt by an affair. That person might feel like the cost of marrying an unfaithful person is much greater than the cost of not marrying a faithful one. So we adjust the threshold downwards:</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb244-1" title="1">threshold &lt;-<span class="st"> </span><span class="fl">.05</span></a>
<a class="sourceLine" id="cb244-2" title="2">classification &lt;-<span class="st"> </span><span class="kw">ifelse</span>(predictTest <span class="op">&gt;</span><span class="st"> </span>threshold,</a>
<a class="sourceLine" id="cb244-3" title="3">                         <span class="st">&quot;Predictunfaithful&quot;</span>, <span class="st">&quot;PredictOK&quot;</span>)</a>
<a class="sourceLine" id="cb244-4" title="4">(b &lt;-<span class="st"> </span><span class="kw">table</span>(classification, testFair<span class="op">$</span>affairYN))</a></code></pre></div>
<pre><code>##                    
## classification        0   1
##   PredictOK          27   3
##   Predictunfaithful 155  55</code></pre>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb246-1" title="1">(correct &lt;-<span class="st"> </span>b[<span class="dv">1</span>,<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>b[<span class="dv">2</span>,<span class="dv">2</span>])</a></code></pre></div>
<pre><code>## [1] 82</code></pre>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb248-1" title="1">(errors &lt;-<span class="st">  </span>b[<span class="dv">1</span>,<span class="dv">2</span>] <span class="op">+</span><span class="st"> </span>b[<span class="dv">2</span>,<span class="dv">1</span>])</a></code></pre></div>
<pre><code>## [1] 158</code></pre>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb250-1" title="1">(accuracy &lt;-<span class="st"> </span>correct<span class="op">/</span>(correct <span class="op">+</span><span class="st"> </span>errors))</a></code></pre></div>
<pre><code>## [1] 0.3416667</code></pre>
<p>The “overall accuracy” - that is, number of correct classifications - drops. But that’s not what we are really interested in, rather, we are interested in minimizing hurt.</p>
<p>Here’s another example: Someone who is very lonely might feel the opposite, and be willing to accept greater substantially greater risk.</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb252-1" title="1">threshold &lt;-<span class="st"> </span><span class="fl">.5</span></a>
<a class="sourceLine" id="cb252-2" title="2">classification &lt;-<span class="st"> </span><span class="kw">ifelse</span>(predictTest <span class="op">&gt;</span><span class="st"> </span>threshold,</a>
<a class="sourceLine" id="cb252-3" title="3">                         <span class="st">&quot;Predictunfaithful&quot;</span>, <span class="st">&quot;PredictOK&quot;</span>)</a>
<a class="sourceLine" id="cb252-4" title="4">(b &lt;-<span class="st"> </span><span class="kw">table</span>(classification, testFair<span class="op">$</span>affairYN))</a></code></pre></div>
<pre><code>##                    
## classification        0   1
##   PredictOK         111  21
##   Predictunfaithful  71  37</code></pre>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb254-1" title="1">(correct &lt;-<span class="st"> </span>b[<span class="dv">1</span>,<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>b[<span class="dv">2</span>,<span class="dv">2</span>])</a></code></pre></div>
<pre><code>## [1] 148</code></pre>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb256-1" title="1">(errors &lt;-<span class="st"> </span>b[<span class="dv">1</span>,<span class="dv">2</span>] <span class="op">+</span><span class="st"> </span>b[<span class="dv">2</span>,<span class="dv">1</span>])</a></code></pre></div>
<pre><code>## [1] 92</code></pre>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb258-1" title="1">(accuracy &lt;-<span class="st"> </span>correct<span class="op">/</span>(correct <span class="op">+</span><span class="st"> </span>errors))</a></code></pre></div>
<pre><code>## [1] 0.6166667</code></pre>
<p>Prediction is higher here - but not much higher than it would be if we raised the threshold even further, and just assumed that everyone can be trusted. Then, our error rate would be 25 percent. When overall predictability is low, it’s often the case that you can maximize correct predictions by simply predicting that everyone will be in the most popular category. Predicting rare events, such as suicides, is particularly difficult.</p>
</div>
<div id="more-confusion" class="section level3">
<h3><span class="header-section-number">19.1.3</span> more confusion</h3>
<p>There is a nice shortcut to generating confusion matrices such as those above using the caret package.</p>
<p>This function describes outcomes in several ways, as there are many languages for describing outcomes in 2 x 2 tables, including Type I vs. Type II errors, Hits vs. False Alarms/False Positives, and Sensitivity vs. Specificity.</p>
<p>In these data, it’s been set up so that</p>
<ul>
<li>hit rate ~ sensitivity ~ (“no affair” | no affair)</li>
<li>correct rejection ~ specificity ~ (“affair” | affair)</li>
</ul>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb260-1" title="1">threshold &lt;-<span class="st"> </span><span class="fl">.5</span></a>
<a class="sourceLine" id="cb260-2" title="2"><span class="co"># syntax for classification in caret is a little different</span></a>
<a class="sourceLine" id="cb260-3" title="3"><span class="co"># (the labels for the actual and predicted scores have to be the same)</span></a>
<a class="sourceLine" id="cb260-4" title="4"><span class="co">#classification &lt;- ifelse(predictTest &gt; threshold,</span></a>
<a class="sourceLine" id="cb260-5" title="5"><span class="co">#                         &quot;Predictunfaithful&quot;, &quot;PredictOK&quot;)</span></a>
<a class="sourceLine" id="cb260-6" title="6">classification &lt;-<span class="st"> </span><span class="kw">ifelse</span>(predictTest <span class="op">&gt;</span><span class="st"> </span>threshold, <span class="dv">1</span>,<span class="dv">0</span>)</a>
<a class="sourceLine" id="cb260-7" title="7"><span class="co"># caret package (newest) requires explicit matching of factors</span></a>
<a class="sourceLine" id="cb260-8" title="8">classification &lt;-<span class="st"> </span><span class="kw">as.factor</span>(classification)</a>
<a class="sourceLine" id="cb260-9" title="9">testFair<span class="op">$</span>affairYN &lt;-<span class="st"> </span><span class="kw">as.factor</span>(testFair<span class="op">$</span>affairYN)</a>
<a class="sourceLine" id="cb260-10" title="10"><span class="kw">confusionMatrix</span>(classification, testFair<span class="op">$</span>affairYN)</a></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   0   1
##          0 111  21
##          1  71  37
##                                           
##                Accuracy : 0.6167          
##                  95% CI : (0.5519, 0.6785)
##     No Information Rate : 0.7583          
##     P-Value [Acc &gt; NIR] : 1               
##                                           
##                   Kappa : 0.1916          
##                                           
##  Mcnemar&#39;s Test P-Value : 3.245e-07       
##                                           
##             Sensitivity : 0.6099          
##             Specificity : 0.6379          
##          Pos Pred Value : 0.8409          
##          Neg Pred Value : 0.3426          
##              Prevalence : 0.7583          
##          Detection Rate : 0.4625          
##    Detection Prevalence : 0.5500          
##       Balanced Accuracy : 0.6239          
##                                           
##        &#39;Positive&#39; Class : 0               
## </code></pre>
</div>
<div id="rocs-and-auc" class="section level3">
<h3><span class="header-section-number">19.1.4</span> ROCs and AUC</h3>
<p>Each of these decision thresholds describes the performance of a model at a particular point. We can combine the thresholds and plot them in Receiver Operating Characteristic (ROC) curves. The area under the curve (AUC) is a great measure of model accuracy, in that it summarizes how effective a classifier is across all possible thresholds.</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb262-1" title="1"><span class="co"># fig.width and fig.height specified to get square plots</span></a>
<a class="sourceLine" id="cb262-2" title="2"><span class="co"># colAUC function gets stats etc</span></a>
<a class="sourceLine" id="cb262-3" title="3">AUCModel &lt;-<span class="st"> </span><span class="kw">colAUC</span>(predictTest, testFair[[<span class="st">&quot;affairYN&quot;</span>]], <span class="dt">plotROC =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<p><img src="DataSciLibArts_files/figure-html/0414model1ROC-1.png" width="480" /></p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb263-1" title="1">AUCModel</a></code></pre></div>
<pre><code>##              [,1]
## 0 vs. 1 0.6662562</code></pre>
</div>
</div>
<div id="another-approach-to-classification-k-nearest-neighbor" class="section level2">
<h2><span class="header-section-number">19.2</span> another approach to classification: k-nearest neighbor</h2>
<p>Real-life social predictions are often guided not by induction or the (optimized) combination of a set of predictor variables. Rather, we often reason by analogy - we might think, for example, that <em>I won’t go out with Fred because he reminds me of Larry, and Larry was kind of a jerk.</em></p>
<p>If regression analysis is an approach to prediction based in our set of variables, <em>k-nearest neighbor</em> analysis instead makes predictions based on observations.</p>
<p>Formally, as described in the documentation for the knn package,</p>
<blockquote>
<p>For each row of the test set, the k nearest (in Euclidean distance) training set vectors are found, and the classification is decided by majority vote, with ties broken at random. (ref).</p>
</blockquote>
<p>In the simplest form of this analysis, we find the nearest thing to a “doppelganger” (a look-alike or near double) for a given observation. So, in the affairs data, if a person is most like someone else in the dataset who has had an affair, we predict an affair, else not.</p>
<div id="application-the-affairs-data" class="section level3">
<h3><span class="header-section-number">19.2.1</span> application: the affairs data</h3>
<p>Begin by loading the affairs data from last time. Using the same seed (33458) means that the same set of training and test cases will be extracted as in the prior analysis</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb265-1" title="1"><span class="kw">data</span>(Fair)</a>
<a class="sourceLine" id="cb265-2" title="2"><span class="co"># one change here: Note the bidirectional pipe to simplify code</span></a>
<a class="sourceLine" id="cb265-3" title="3"><span class="co"># use only when you are sure that your file update is ok</span></a>
<a class="sourceLine" id="cb265-4" title="4">Fair <span class="op">%&lt;&gt;%</span><span class="st"> </span><span class="co"># &lt;- Fair %&gt;% </span></a>
<a class="sourceLine" id="cb265-5" title="5"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">affairYN =</span></a>
<a class="sourceLine" id="cb265-6" title="6"><span class="co"># nbaffairs is set up as a factor</span></a>
<a class="sourceLine" id="cb265-7" title="7"><span class="co"># to allow confusionmatrix to run</span></a>
<a class="sourceLine" id="cb265-8" title="8">               <span class="kw">as.factor</span>(<span class="kw">ifelse</span>(nbaffairs <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb265-9" title="9"><span class="co"># unlike the lm and glm commands, knn will not automatically create our dummy # variables for us. so we need to do this manually.</span></a>
<a class="sourceLine" id="cb265-10" title="10"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">sexMale =</span> <span class="kw">ifelse</span>(sex <span class="op">==</span><span class="st"> &quot;female&quot;</span>, <span class="dv">0</span>, <span class="dv">1</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb265-11" title="11"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">childyes =</span> <span class="kw">ifelse</span>(child <span class="op">==</span><span class="st"> &quot;no&quot;</span>, <span class="dv">0</span>, <span class="dv">1</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb265-12" title="12"><span class="st">    </span><span class="kw">select</span>(<span class="op">-</span>(<span class="kw">c</span>(sex,child,nbaffairs)))</a>
<a class="sourceLine" id="cb265-13" title="13"></a>
<a class="sourceLine" id="cb265-14" title="14"><span class="kw">set.seed</span>(<span class="dv">33458</span>)</a>
<a class="sourceLine" id="cb265-15" title="15">n &lt;-<span class="st"> </span><span class="kw">nrow</span>(Fair)</a>
<a class="sourceLine" id="cb265-16" title="16">trainIndex &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span>n, <span class="dt">size =</span> <span class="kw">round</span>(<span class="fl">0.6</span><span class="op">*</span>n), <span class="dt">replace =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb265-17" title="17"><span class="co"># create training and test samples</span></a>
<a class="sourceLine" id="cb265-18" title="18">trainFair &lt;-<span class="st"> </span>Fair[trainIndex ,]</a>
<a class="sourceLine" id="cb265-19" title="19">testFair &lt;-<span class="st"> </span>Fair[<span class="op">-</span>trainIndex ,]</a></code></pre></div>
<p>To run a k-nearest neighbor analysis, we need three inputs: our predictors in the training data, our predictors in the test data, and our outcome/classes in the training data.</p>
<p>Here, as in the regression analysis in the last chapter, we can generate a confusion matrix to assess the accuracy of prediction:</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb266-1" title="1"><span class="kw">set.seed</span>(<span class="dv">33458</span>)</a>
<a class="sourceLine" id="cb266-2" title="2">trainPredictors &lt;-<span class="st"> </span>trainFair <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb266-3" title="3"><span class="st">    </span><span class="kw">select</span>(<span class="op">-</span>affairYN)</a>
<a class="sourceLine" id="cb266-4" title="4">testPredictors &lt;-<span class="st"> </span>testFair <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb266-5" title="5"><span class="st">    </span><span class="kw">select</span>(<span class="op">-</span>affairYN)</a>
<a class="sourceLine" id="cb266-6" title="6">knnAffair &lt;-<span class="st"> </span><span class="kw">knn</span>(trainPredictors, <span class="co"># training data</span></a>
<a class="sourceLine" id="cb266-7" title="7">             testPredictors, <span class="co"># test data</span></a>
<a class="sourceLine" id="cb266-8" title="8">             trainFair<span class="op">$</span>affairYN, <span class="co"># class</span></a>
<a class="sourceLine" id="cb266-9" title="9">             <span class="dv">1</span> <span class="co"># number of neighbors</span></a>
<a class="sourceLine" id="cb266-10" title="10">             )</a>
<a class="sourceLine" id="cb266-11" title="11">b&lt;-<span class="kw">confusionMatrix</span>(knnAffair, testFair<span class="op">$</span>affairYN)</a>
<a class="sourceLine" id="cb266-12" title="12">b</a></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   0   1
##          0 143  32
##          1  39  26
##                                           
##                Accuracy : 0.7042          
##                  95% CI : (0.6421, 0.7611)
##     No Information Rate : 0.7583          
##     P-Value [Acc &gt; NIR] : 0.9772          
##                                           
##                   Kappa : 0.2247          
##                                           
##  Mcnemar&#39;s Test P-Value : 0.4764          
##                                           
##             Sensitivity : 0.7857          
##             Specificity : 0.4483          
##          Pos Pred Value : 0.8171          
##          Neg Pred Value : 0.4000          
##              Prevalence : 0.7583          
##          Detection Rate : 0.5958          
##    Detection Prevalence : 0.7292          
##       Balanced Accuracy : 0.6170          
##                                           
##        &#39;Positive&#39; Class : 0               
## </code></pre>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb268-1" title="1">b[[<span class="st">&quot;overall&quot;</span>]][[<span class="st">&quot;Accuracy&quot;</span>]]</a></code></pre></div>
<pre><code>## [1] 0.7041667</code></pre>
</div>
<div id="from-one-doppelganger-to-many" class="section level3">
<h3><span class="header-section-number">19.2.2</span> from one doppelganger to many</h3>
<p>In the above code, we used a k-nearest neighbor analysis based on a single ‘neighbor’ (k = 1). Can we improve prediction by considering more than 1 neighbor?</p>
</div>
<div id="the-bayesian-classifier" class="section level3">
<h3><span class="header-section-number">19.2.3</span> the Bayesian classifier</h3>
<p>Lisa is a doctor whose patients often have post-surgical pain. Their suffering is real, but effective pain medications such as OxyContin have a high likelihood of leading to abuse and addiction. She has two bits of information about a patient, his or her age (say that we have this in ten levels, corresponding to decades of age, so that the first level is “under 20” and that the last level is “over 100”), and his or her self-report of pain, also on a 10 point scale.</p>
<p>Assume that Lisa wants to prescribe the medication to all patients who would not abuse it, and not prescribe the medication to anyone who would.</p>
<p>Assume that Lisa knew the entire matrix of conditional probabilities,</p>
<blockquote>
<p>P (addiction | “age &lt; 20” &amp; “pain = 1”) = .34</p>
<p>P (addiction | “age &lt; 20” &amp; “pain = 2”) = .26</p>
<p>… P (addiction | “age &gt; 100” &amp; “pain = 10”) = .09</p>
</blockquote>
<p>In this case she would prescribe the drug for every case where the conditional probability was greater than .5, and never otherwise. This is called the <strong>Bayesian classifier</strong>, and if we have the entire matrix of conditional probabilities we could do no better.</p>
<p>In real world problems, we are typically dealing with many predictors, and we don’t have the full matrix of conditional probabilities. But this two predictor case “sets up” the illustration drawn from <span class="citation">(James et al. <a href="#ref-james2013introduction" role="doc-biblioref">2013</a><a href="#ref-james2013introduction" role="doc-biblioref">a</a>)</span>.</p>
<div class="figure">
<img src="knnTwovaluesfromJames2013.PNG" alt="Figure 10.1: Comparing two values of k (From (???))" />
<p class="caption">Figure 10.1: Comparing two values of k (From <span class="citation">(<span class="citeproc-not-found" data-reference-id="jamesintroduction"><strong>???</strong></span>)</span>)</p>
</div>
<p>In the figure above, assume that the horizontal and vertical axes correspond to scores on the two predictors (age and pain). The orange and blue colored dots correspond to cases of abuse and non-abuse in the training data. The dashed line is the Bayesian classifier. The solid line is the k-nn decision boundary, which distinguishes the regions in which we will predict abuse and non abuse in the test data. We see that when k is small (a single neighbor), prediction is flexible, non-linear, and that as k increases, the boundary differentiating the decision to prescribe and not prescribe becomes more nearly linear.</p>
<p>But what value of k is optimal?</p>
</div>
<div id="back-to-the-affairs-data" class="section level3">
<h3><span class="header-section-number">19.2.4</span> Back to the affairs data</h3>
<p>To test a range of values, we can first set up our knn analysis as a function (compare this code with the code in the prior section).</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb270-1" title="1">trainPredictors &lt;-<span class="st"> </span>trainFair <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb270-2" title="2"><span class="st">    </span><span class="kw">select</span>(<span class="op">-</span>affairYN)</a>
<a class="sourceLine" id="cb270-3" title="3">testPredictors &lt;-<span class="st"> </span>testFair <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb270-4" title="4"><span class="st">    </span><span class="kw">select</span>(<span class="op">-</span>affairYN)</a>
<a class="sourceLine" id="cb270-5" title="5">knnFairdata &lt;-<span class="st"> </span><span class="cf">function</span> (k) {</a>
<a class="sourceLine" id="cb270-6" title="6">    <span class="kw">set.seed</span>(<span class="dv">33458</span>)</a>
<a class="sourceLine" id="cb270-7" title="7">    knnAffair &lt;-<span class="st"> </span><span class="kw">knn</span>(trainPredictors, <span class="co"># training data</span></a>
<a class="sourceLine" id="cb270-8" title="8">                 testPredictors, <span class="co"># test data</span></a>
<a class="sourceLine" id="cb270-9" title="9">                 trainFair<span class="op">$</span>affairYN, <span class="co"># class</span></a>
<a class="sourceLine" id="cb270-10" title="10">                 k <span class="co"># number of neighbors</span></a>
<a class="sourceLine" id="cb270-11" title="11">                 )</a>
<a class="sourceLine" id="cb270-12" title="12">    b&lt;-<span class="kw">confusionMatrix</span>(knnAffair, testFair<span class="op">$</span>affairYN)</a>
<a class="sourceLine" id="cb270-13" title="13">    b[[<span class="st">&quot;overall&quot;</span>]][[<span class="st">&quot;Accuracy&quot;</span>]]</a>
<a class="sourceLine" id="cb270-14" title="14">}</a></code></pre></div>
<p>We run the function on k = 1 and k = 2 to test it:</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb271-1" title="1"><span class="kw">knnFairdata</span>(<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 0.7041667</code></pre>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb273-1" title="1"><span class="kw">knnFairdata</span>(<span class="dv">2</span>)</a></code></pre></div>
<pre><code>## [1] 0.6958333</code></pre>
<p>Now we can apply it to as many as 100 values of k, using the purrr::map command:</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb275-1" title="1">kAccuracy &lt;-<span class="st"> </span>(<span class="kw">map_dbl</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">100</span>,knnFairdata)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># map the knnFunction onto numbers 1-100</span></a>
<a class="sourceLine" id="cb275-2" title="2"><span class="st">    </span><span class="kw">as_tibble</span>() <span class="op">%&gt;%</span><span class="st">  </span><span class="co"># then a tibble so we can do a quick plot</span></a>
<a class="sourceLine" id="cb275-3" title="3"><span class="st">    </span><span class="kw">rename</span>(<span class="dt">Accuracy =</span> <span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb275-4" title="4"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">k =</span> <span class="kw">seq_along</span>(Accuracy))</a></code></pre></div>
<p>We can graph this, using the syntax from the beginning of the class:</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb276-1" title="1">kAccuracy <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb276-2" title="2"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(k, Accuracy)) <span class="op">+</span><span class="co">#%&gt;% </span></a>
<a class="sourceLine" id="cb276-3" title="3"><span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb276-4" title="4"><span class="st">    </span><span class="kw">ggtitle</span>(<span class="st">&quot;Overall accuracy for varying levels of k&quot;</span>)</a></code></pre></div>
<p><img src="DataSciLibArts_files/figure-html/unnamed-chunk-117-1.png" width="672" /></p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb277-1" title="1"><span class="co"># This pulls out the maximum accuracy, and the value of k for which it occurs:</span></a>
<a class="sourceLine" id="cb277-2" title="2">(ka &lt;-<span class="st"> </span><span class="kw">which.max</span>(kAccuracy<span class="op">$</span>Accuracy))</a></code></pre></div>
<pre><code>## [1] 33</code></pre>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb279-1" title="1">(kb &lt;-<span class="st"> </span><span class="kw">max</span>(kAccuracy<span class="op">$</span>Accuracy))</a></code></pre></div>
<pre><code>## [1] 0.7583333</code></pre>
</div>
<div id="avoiding-capitalization-on-chance-again" class="section level3">
<h3><span class="header-section-number">19.2.5</span> avoiding capitalization on chance (again)</h3>
<p>In these data, with this split of training and test (and this initial seed) the maximum predictability occurs at k = 33, with an overall accuracy of 0.7583333.</p>
<p>Would this hold if we used a different random split? Remember, here, we have tested not one model, but 100 of them, then chosen the best one. The peak in the curve at 33 may well be due to chance characteristics of the test data.</p>
<p>We could address this empirically using one of several techniques. One approach is to have a third independent sample on which to test the accuracy of prediction at k = 33. This would require the separate validation sample that was introduced in the last chapter.</p>
<p>In the following block, I resplit the Fair data, using proportions of 60%, 30%, 10%. These values are likely not optimal given the (relatively small) size of the Fair data, but will work to illustrate the approach:</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb281-1" title="1"><span class="kw">set.seed</span>(<span class="dv">33458</span>)</a>
<a class="sourceLine" id="cb281-2" title="2">threeWaySplit &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>, <span class="dt">size =</span> <span class="kw">nrow</span>(Fair),</a>
<a class="sourceLine" id="cb281-3" title="3">                        <span class="dt">prob =</span> <span class="kw">c</span>(<span class="fl">0.6</span>,<span class="fl">0.3</span>,<span class="fl">0.1</span>),</a>
<a class="sourceLine" id="cb281-4" title="4">                        <span class="dt">replace =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb281-5" title="5">trainFair2 &lt;-<span class="st"> </span>Fair[threeWaySplit <span class="op">==</span><span class="st"> </span><span class="dv">1</span>,]</a>
<a class="sourceLine" id="cb281-6" title="6">testFair2 &lt;-<span class="st"> </span>Fair[threeWaySplit <span class="op">==</span><span class="st"> </span><span class="dv">2</span>,]</a>
<a class="sourceLine" id="cb281-7" title="7">validFair2 &lt;-<span class="st"> </span>Fair[threeWaySplit <span class="op">==</span><span class="st"> </span><span class="dv">3</span>,]</a></code></pre></div>
<p>I tweak my function here to use the new data, then run it 100 times as before.</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb282-1" title="1">trainPredictors &lt;-<span class="st"> </span>trainFair2 <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb282-2" title="2"><span class="st">    </span><span class="kw">select</span>(<span class="op">-</span>affairYN)</a>
<a class="sourceLine" id="cb282-3" title="3">testPredictors &lt;-<span class="st"> </span>testFair2 <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb282-4" title="4"><span class="st">    </span><span class="kw">select</span>(<span class="op">-</span>affairYN)</a>
<a class="sourceLine" id="cb282-5" title="5">knnFairdata2 &lt;-<span class="st"> </span><span class="cf">function</span> (k) {</a>
<a class="sourceLine" id="cb282-6" title="6">    <span class="kw">set.seed</span>(<span class="dv">33458</span>)</a>
<a class="sourceLine" id="cb282-7" title="7">    knnAffair &lt;-<span class="st"> </span><span class="kw">knn</span>(trainPredictors, <span class="co"># training data</span></a>
<a class="sourceLine" id="cb282-8" title="8">             testPredictors, <span class="co"># test data</span></a>
<a class="sourceLine" id="cb282-9" title="9">             trainFair2<span class="op">$</span>affairYN, <span class="co"># class</span></a>
<a class="sourceLine" id="cb282-10" title="10">             k <span class="co"># number of neighbors</span></a>
<a class="sourceLine" id="cb282-11" title="11">             )</a>
<a class="sourceLine" id="cb282-12" title="12">    b&lt;-<span class="kw">confusionMatrix</span>(knnAffair, testFair2<span class="op">$</span>affairYN)</a>
<a class="sourceLine" id="cb282-13" title="13">    b[[<span class="st">&quot;overall&quot;</span>]][[<span class="st">&quot;Accuracy&quot;</span>]]</a>
<a class="sourceLine" id="cb282-14" title="14">}</a>
<a class="sourceLine" id="cb282-15" title="15">kAccuracy &lt;-<span class="st"> </span>(<span class="kw">map_dbl</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">100</span>,knnFairdata2)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># map the knnFunction onto numbers 1-100</span></a>
<a class="sourceLine" id="cb282-16" title="16"><span class="st">    </span><span class="kw">as_tibble</span>() <span class="op">%&gt;%</span><span class="st">  </span><span class="co"># then a tibble so we can do a quick plot</span></a>
<a class="sourceLine" id="cb282-17" title="17"><span class="st">    </span><span class="kw">rename</span>(<span class="dt">Accuracy=</span>value) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb282-18" title="18"><span class="st">    </span><span class="kw">mutate</span> (<span class="dt">k =</span> <span class="kw">seq_along</span>(Accuracy))</a>
<a class="sourceLine" id="cb282-19" title="19">(ka2 &lt;-<span class="st"> </span><span class="kw">which.max</span>(kAccuracy<span class="op">$</span>Accuracy))</a></code></pre></div>
<pre><code>## [1] 15</code></pre>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb284-1" title="1">(kb2 &lt;-<span class="st"> </span><span class="kw">max</span>(kAccuracy<span class="op">$</span>Accuracy))</a></code></pre></div>
<pre><code>## [1] 0.7802198</code></pre>
<p>So here, on the (contaminated) test data, the maximum predictability occurs at k = 15, with an overall accuracy of 0.7802198. We apply this back to the validation data by pulling the knn code out of the function, and running it just once against the validation data:</p>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb286-1" title="1">knnAffair &lt;-<span class="st"> </span><span class="kw">knn</span>(trainFair2[,<span class="op">-</span><span class="dv">7</span>], <span class="co"># training data</span></a>
<a class="sourceLine" id="cb286-2" title="2">             validFair2[,<span class="op">-</span><span class="dv">7</span>], <span class="co"># VALIDATION data</span></a>
<a class="sourceLine" id="cb286-3" title="3">             trainFair2<span class="op">$</span>affairYN, <span class="co"># class</span></a>
<a class="sourceLine" id="cb286-4" title="4">             ka2 <span class="co"># number of neighbors</span></a>
<a class="sourceLine" id="cb286-5" title="5">             )</a>
<a class="sourceLine" id="cb286-6" title="6">b &lt;-<span class="st"> </span><span class="kw">confusionMatrix</span>(knnAffair, validFair2<span class="op">$</span>affairYN)</a>
<a class="sourceLine" id="cb286-7" title="7">(kb3 &lt;-<span class="st"> </span>b[[<span class="st">&quot;overall&quot;</span>]][[<span class="st">&quot;Accuracy&quot;</span>]])</a></code></pre></div>
<pre><code>## [1] 0.703125</code></pre>
<p>The overall predictability using the k-nearest neighbor analysis on the clean validation data, is now 0.703125.</p>
<p>You might note that in our two splits of the Fair data - the two-way split of 60% Training and 40% Test, and the three-way split of 60% Training, 30% Test, 10% Validation, we got two different solutions to the question of the ‘optimal k’ (i.e., 33 and 15). With larger sample sizes, these values would be more stable.</p>
</div>
<div id="the-multinomial-case" class="section level3">
<h3><span class="header-section-number">19.2.6</span> the multinomial case</h3>
<p>A final comment on the k-nearest neighbors approach: You can extend this to classification problems in which we are predicting not just a dichotomous outcome, but a multinomial one - such as a personality type or college concentration.</p>

<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb288-1" title="1">knitr<span class="op">::</span>opts_chunk<span class="op">$</span><span class="kw">set</span>(<span class="dt">echo =</span> <span class="ot">TRUE</span>, <span class="dt">warn =</span> <span class="ot">FALSE</span>, <span class="dt">message =</span> <span class="ot">FALSE</span>) </a>
<a class="sourceLine" id="cb288-2" title="2"><span class="kw">library</span>(citr)</a>
<a class="sourceLine" id="cb288-3" title="3"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb288-4" title="4"><span class="kw">library</span>(Ecdat) <span class="co"># for Swiss data</span></a>
<a class="sourceLine" id="cb288-5" title="5"><span class="kw">library</span>(rpart) <span class="co"># for decision trees</span></a>
<a class="sourceLine" id="cb288-6" title="6"><span class="kw">library</span>(kableExtra)</a></code></pre></div>
</div>
</div>
</div>
<h3> references</h3>
<div id="refs" class="references">
<div id="ref-james2013introduction">
<p>James, Gareth, Daniela Witten, Trevor Hastie, and Robert Tibshirani. 2013a. <em>An Introduction to Statistical Learning</em>. Vol. 112. Springer.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="cross-validation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
